name: Quality

on: ['push', 'pull_request']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup PHP
        uses: ./.github/actions/setup
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: Install Node Dependencies
        run: npm ci
      - name: 🕵️‍♂️ Run Laravel Pint
        run: composer test:lint
      - name: 🕵️‍♂️ Run PHPStan
        run: composer test:types
      - name: 🕵️‍♂️ Run Type coverage
        run: composer test:type-coverage
